### ISSUE TITLE
ISSUE IN Loading the vectors

### ISSUE THREAD

**Issue by minesh94** [tttthomasssss/apt-toolkit#1]
vectors = vector_utils.load_vector_cache('APT_wikipedia_clean_shift-10.dill', filetype='dill')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/minesh/Desktop/t/lib/python3.5/site-packages/apt_toolkit-0.1.0-py3.5.egg/apt_toolkit/utils/vector_utils.py", line 108, in load_vector_cache
  File "/home/minesh/Desktop/t/lib/python3.5/site-packages/dill/dill.py", line 288, in load
    obj = pik.load()
  File "/home/minesh/Desktop/t/lib/python3.5/site-packages/dill/dill.py", line 445, in find_class
    return StockUnpickler.find_class(self, module, name)
ImportError: No module named 'apt_toolkit.weighting'

This is the error I am getting while loading the file in 1st line. Please help resolve

**Comment by tttthomasssss** [comment]
Hi @minesh94, thanks for reporting this issue! 

You can pull again now - it should be fixed

**Comment by minesh94** [comment]
I have some queries. It would be really helpful if you would answer them.

1. You have taken SPMI as weights. Also it has been mentioned in the paper
that we can take probabilities and counts as well. If we take probabilities
how do you ensure that the composed vector weights won't go more than 1 or
violate the probabilistic space of lying between 0 and 1.
2. Also for count vectors, do we perform normalization or use counts as
they are.
